sudo: required
dist: build
language: node_js
node_js:
  - "8"
install:
  - yarn
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN
  on:
    branch: master